### ISSUE TITLE
Work towards more inclusive, open branch naming

### ISSUE THREAD

**Issue by epuration** [Scyntrus/WarframeRivenScanner#1]
Hi, I noticed that this project is missing a COC, and that it's main branch is named `master`, which can be especially triggering to many people in the USA.

I propose adopting a [COC](https://www.contributor-covenant.org/), and renaming the main branch to `main`.

Yours in wokeness,

Epuration

**Comment by Scyntrus** [comment]
As someone who's ancestors were enslaved by the Ottoman Empire, I find this historical revisionism that erases such history to be offensive.
